version: "3.3"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql1
    hostname: sql1
    ports:
      - "80:80"
      - "1433:1433"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
